[project]
name = "sonar-ot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bert-score>=0.3.13",
    "datasets>=3.6.0",
    "diffusers>=0.33.1",
    "fairseq>=0.12.2",
    "kaleido==0.2.1",
    "librosa>=0.11.0",
    "orion[nevergrad,profet]>=0.2.7",
    "pandas>=2.2.3",
    "ruff>=0.11.9",
    "sonar-space>=0.4.0",
    "speechbrain>=1.0.3",
    "torchcfm>=1.0.7",
    "transformers>=4.51.3",
    "umap-learn>=0.5.7",
]
